#!/bin/sh
# Copyright 2017 Marc-Antoine Ruel. All Rights Reserved. Use of this
# source code is governed by a BSD-style license that can be found in the
# LICENSE file.

# Run as:
#   curl -sSL https://raw.githubusercontent.com/periph/bootstrap/master/enable_sendmail.sh | bash

set -eu

# Requires two arguments:
# - hostname, like foo.example.com
# - destination email address, like foo+automated@gmail.com
HOST=$1
DEST=$2

echo "- Installing postfix"
# This is needed otherwise postfix will bring a UI.
echo "postfix postfix/main_mailer_type string 'No Config'" | sudo debconf-set-selections

# If you are space constrained, here's the approximative size:
# bsd-mailx:            3.8MB
# postfix:              570kB
sudo DEBIAN_FRONTEND=noninteractive apt install -yq bsd-mailx postfix


# Inspired by:
# https://blog.dantup.com/2016/04/setting-up-raspberry-pi-raspbian-jessie-to-send-email/
echo "- Configure outgoing emails"
sudo tee /etc/postfix/main.cf > /dev/null <<EOF
# Generated by https://github.com/periph/bootstrap

# Where to read account aliases, used to map all emails onto one account
# and then on to a real email address
alias_maps = hash:/etc/aliases

# This sets the hostname, which will be used for outgoing email
myhostname = $HOST

# This is the mailserver to connect to deliver email
# NOTE: This must be the MX server for the account you wish to deliver email to
# or an open relay (but you hopefully won't find one of them). In my case, this
# is Google's first MX server (which can be found by doing an MX lookup on my
# domain).
relayhost = aspmx.l.google.com

# Do not relay emails.
inet_interfaces = loopback-only

# Disable IPv6. See
# https://blog.dantup.com/2016/04/setting-up-raspberry-pi-raspbian-jessie-to-send-email/
# for rationale.
inet_protocols = ipv4
EOF


sudo sed -i '/root:/d' /etc/aliases
echo "root: $DEST" | sudo tee --append /etc/aliases
sudo newaliases


echo "- Enabling email for unattended-upgrades"
sudo tee /etc/apt/apt.conf.d/91periph_email > /dev/null <<EOF
// Generated by https://github.com/periph/bootstrap
Unattended-Upgrade::Mail "root";
EOF

sudo service postfix restart

echo "- Sending a test email"
cat <<EOF | sendmail -t
FROM: enable_sendmail.sh
TO: root
Subject: $HOST is configured!

This confirms sendmail works.
EOF

echo "- Check $DEST for an email from $HOST"
echo "- Don't forget to configure the SPF record; it should look like:"
echo "  v=spf1 include:_spf.google.com a:$DEST ~all"
